# Generated by Django 4.2.26 on 2025-11-25 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('discord_id', models.CharField(max_length=20, unique=True)),
                ('discord_username', models.CharField(max_length=100)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='URL用の識別子（例: apex, valorant）', max_length=50, unique=True)),
                ('name', models.CharField(help_text='ゲーム名', max_length=100)),
                ('icon', models.URLField(blank=True, help_text='ゲームアイコンURL', max_length=500)),
                ('color', models.CharField(default='#6366f1', help_text='テーマカラー（例: #DA292A）', max_length=7)),
                ('max_players', models.PositiveIntegerField(default=4, help_text='最大パーティ人数')),
                ('is_active', models.BooleanField(default=True, help_text='サイトに表示するか')),
                ('order', models.PositiveIntegerField(default=0, help_text='表示順（小さいほど上）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='サイト上での表示名', max_length=50)),
                ('platform', models.CharField(choices=[('pc', 'PC'), ('ps', 'PlayStation'), ('xbox', 'Xbox'), ('switch', 'Switch'), ('mobile', 'Mobile')], default='pc', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='自己紹介', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('main_game', models.ForeignKey(blank=True, help_text='メインでプレイするゲーム', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(help_text='ゲーム内のプレイヤーID', max_length=100)),
                ('rank', models.CharField(blank=True, help_text='ランク（任意）', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to='accounts.game')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to='accounts.profile')),
            ],
            options={
                'unique_together': {('profile', 'game')},
            },
        ),
    ]
