# Generated by Django 4.2.26 on 2025-11-25 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='募集タイトル', max_length=100)),
                ('description', models.TextField(blank=True, help_text='詳細説明', max_length=500)),
                ('platform', models.CharField(choices=[('pc', 'PC'), ('ps', 'PlayStation'), ('xbox', 'Xbox'), ('switch', 'Switch'), ('mobile', 'Mobile'), ('crossplay', 'クロスプレイ')], default='pc', max_length=20)),
                ('max_players', models.PositiveIntegerField(default=4, help_text='募集人数（自分含む）')),
                ('rank', models.CharField(blank=True, help_text='ランク条件', max_length=50)),
                ('voice_chat', models.BooleanField(default=False, help_text='ボイスチャット必須か')),
                ('status', models.CharField(choices=[('open', '募集中'), ('closed', '締切'), ('cancelled', 'キャンセル')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='accounts.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', '参加中'), ('left', '離脱')], default='joined', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='accounts.recruitment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recruitment', 'user')},
            },
        ),
    ]
