# Generated by Django 4.2.26 on 2025-11-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountManager',
        ),
    ]
