# Generated by Django 4.2.26 on 2025-11-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recruitment_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.CharField(default='pc,ps,xbox,switch,mobile', help_text='対応プラットフォーム（カンマ区切り: pc,ps,xbox,switch,mobile）', max_length=100),
        ),
    ]
