# Generated by Django 4.2.26 on 2025-11-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_game_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.CharField(default='pc,ps,xbox,switch,mobile,crossplay', help_text='対応プラットフォーム（カンマ区切り: pc,ps,xbox,switch,mobile,crossplay）', max_length=100),
        ),
    ]
