# Generated by Django 4.2.26 on 2025-11-27 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_game_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankname', models.CharField(help_text='ランク名', max_length=100)),
                ('rankorder', models.PositiveIntegerField()),
                ('icon', models.URLField(blank=True, help_text='ランクアイコンURL', max_length=500)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='accounts.game')),
            ],
            options={
                'ordering': ['rankorder'],
                'unique_together': {('game', 'rankname')},
            },
        ),
    ]
