# Generated by Django 4.2.26 on 2025-11-27 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_gamerank'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiotAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(help_text='統一識別子', max_length=100, unique=True)),
                ('game_name', models.CharField(help_text='RIOT ID', max_length=100)),
                ('tag_line', models.CharField(help_text='タグライン', max_length=100)),
                ('summoner_id', models.CharField(blank=True, help_text='サモナーID', max_length=100)),
                ('lol_account_id', models.CharField(blank=True, help_text='アカウントID', max_length=100)),
                ('region', models.CharField(choices=[('ap', 'Asia Pacific'), ('eu', 'Europe'), ('na', 'North America'), ('kr', 'Korea'), ('jp', 'Japan'), ('br', 'Brazil'), ('latam', 'Latin America'), ('oce', 'Oceania'), ('me', 'Middle East')], help_text='リージョン', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riot_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoLRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_type', models.CharField(choices=[('RANKED_SOLO_5x5', 'ソロ/デュオ'), ('RANKED_FLEX_SR', 'フレックス')], help_text='キュー種別', max_length=20)),
                ('tier', models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('EMERALD', 'Emerald'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master'), ('GRANDMASTER', 'Grandmaster'), ('CHALLENGER', 'Challenger')], help_text='ランク', max_length=20)),
                ('rank', models.CharField(help_text='I, II, III, IV', max_length=5)),
                ('league_points', models.IntegerField(default=0, help_text='LP')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('riot_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='accounts.riotaccount')),
            ],
            options={
                'unique_together': {('riot_account', 'queue_type')},
            },
        ),
    ]
