# Generated by Django 4.2.26 on 2025-12-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_riotaccount_lolrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_message_id', models.CharField(blank=True, help_text='DiscordメッセージID', max_length=30)),
                ('discord_channel_id', models.CharField(help_text='DiscordチャンネルID', max_length=30)),
                ('discord_server_id', models.CharField(help_text='DiscordサーバーID', max_length=30)),
                ('discord_owner_id', models.CharField(help_text='募集者のID', max_length=30)),
                ('discord_owner_username', models.CharField(help_text='募集者の名前', max_length=30)),
                ('title', models.CharField(help_text='募集タイトル', max_length=100)),
                ('description', models.TextField(blank=True, help_text='詳細説明', max_length=500)),
                ('max_slots', models.PositiveIntegerField(default=4, help_text='最大募集人数（自分含む）')),
                ('current_slots', models.PositiveIntegerField(default=0, help_text='現在の参加者数')),
                ('participants', models.TextField(default='[]', help_text='参加者リスト')),
                ('status', models.CharField(choices=[('open', '募集中'), ('closed', '締め切り'), ('cancelled', 'キャンセル')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.game')),
            ],
            options={
                'verbose_name': 'Discord募集',
                'verbose_name_plural': 'Discord募集',
                'ordering': ['-created_at'],
            },
        ),
    ]
