# Generated by Django 4.2.26 on 2025-12-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_discordrecruitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordrecruitment',
            name='participants',
            field=models.TextField(default='[]', help_text='参加者リスト'),
        ),
    ]
