# Generated by Django 4.2.26 on 2025-12-01 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_discordrecruitment_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_server_id', models.CharField(help_text='DiscordサーバーID', max_length=30, unique=True)),
                ('discord_server_name', models.CharField(blank=True, help_text='サーバー名', max_length=100)),
                ('default_max_slots', models.PositiveIntegerField(default=3, help_text='デフォルト募集人数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(help_text='このサーバーのゲーム', on_delete=django.db.models.deletion.CASCADE, to='accounts.game')),
            ],
            options={
                'verbose_name': 'Discordサーバー設定',
                'verbose_name_plural': 'Discordサーバー設定',
            },
        ),
    ]
