# Generated by Django 4.2.26 on 2025-12-02 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_discordserversetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserversetting',
            name='available_voice_channels',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='discordserversetting',
            name='voice_category_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VoiceChannelParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.CharField(max_length=30)),
                ('discord_username', models.CharField(max_length=100)),
                ('voice_channel_id', models.CharField(max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vc_participations', to='accounts.discordrecruitment')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_discord_id', models.CharField(max_length=30)),
                ('rater_discord_username', models.CharField(max_length=100)),
                ('rated_discord_id', models.CharField(max_length=30)),
                ('rated_discord_username', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('is_auto_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.discordrecruitment')),
            ],
            options={
                'unique_together': {('recruitment', 'rater_discord_id', 'rated_discord_id')},
            },
        ),
    ]
