# Generated by Django 4.2.26 on 2025-12-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_discordserversetting_available_voice_channels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordrecruitment',
            name='description',
        ),
        migrations.AddField(
            model_name='discordrecruitment',
            name='rank',
            field=models.CharField(blank=True, help_text='ランク条件', max_length=50),
        ),
    ]
