# Generated by Django 4.2.26 on 2025-12-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_discordrecruitment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bannerUrl',
            field=models.URLField(blank=True, help_text='ゲームバナーURL', max_length=500),
        ),
    ]
