# Generated by Django 4.2.26 on 2025-12-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_game_bannerurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordrecruitment',
            name='vc_channel_id',
            field=models.CharField(blank=True, help_text='VCチャンネルID', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='discordrecruitment',
            name='status',
            field=models.CharField(choices=[('open', '募集中'), ('ongoing', '進行中'), ('closed', '締め切り'), ('cancelled', 'キャンセル')], default='open', max_length=20),
        ),
    ]
