# Generated by Django 4.2.26 on 2025-12-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_discordrecruitment_vc_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voicechannelparticipation',
            options={'verbose_name': 'ボイスチャンネル参加履歴', 'verbose_name_plural': 'ボイスチャンネル参加履歴'},
        ),
        migrations.AlterField(
            model_name='discordrecruitment',
            name='rank',
            field=models.CharField(blank=True, help_text='ランク条件', max_length=10),
        ),
        migrations.AlterField(
            model_name='discordrecruitment',
            name='title',
            field=models.CharField(help_text='募集タイトル', max_length=20),
        ),
    ]
