# Generated by Django 4.2.26 on 2025-12-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_voicechannelparticipation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserversetting',
            name='recruitment_channel_id',
            field=models.CharField(blank=True, help_text='フロントからの募集投稿先チャンネル', max_length=30),
        ),
        migrations.AddField(
            model_name='discordserversetting',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Discord Webhook URL', max_length=500),
        ),
    ]
